{
  "uid" : "6eaba313918cbcd8",
  "name" : "test_add_group[None:nameUL;headerO6U9?.z8;&;footero`'a]",
  "fullName" : "test.test_add_group#test_add_group",
  "historyId" : "ef0e48537bd2d07a714771ce63695c81",
  "time" : {
    "start" : 1618228896970,
    "stop" : 1618228897959,
    "duration" : 989
  },
  "status" : "failed",
  "statusMessage" : "AssertionError: assert [1:;;, 2:name...-So8O|B}, ...] == [1:;;, 2:name...-So8O|B}, ...]\n  Left contains one more item: None:nameUL;headerO6U9?.z8;&;footero`'a\n  Use -v to get the full diff",
  "statusTrace" : "app = <fixture.application.Application object at 0x0000018AD5CB7700>\ndb = <fixture.db.DbFixture object at 0x0000018AD5CB7670>\njson_groups = None:nameUL;headerO6U9?.z8;&;footero`'a\n\n    def test_add_group(app, db, json_groups):\n        group = json_groups\n        old_groups = db.get_group_list()\n        app.group.create(group)\n        new_groups = db.get_group_list()\n        old_groups.append(group)\n>       assert sorted(old_groups, key=Group.id_or_max) == sorted(new_groups, key=Group.id_or_max)\nE       AssertionError: assert [1:;;, 2:name...-So8O|B}, ...] == [1:;;, 2:name...-So8O|B}, ...]\nE         Left contains one more item: None:nameUL;headerO6U9?.z8;&;footero`'a\nE         Use -v to get the full diff\n\ntest\\test_add_group.py:11: AssertionError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "db",
    "time" : {
      "start" : 1618228885494,
      "stop" : 1618228885499,
      "duration" : 5
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false,
    "stepsCount" : 0
  }, {
    "name" : "stop",
    "time" : {
      "start" : 1618228885494,
      "stop" : 1618228885494,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false,
    "stepsCount" : 0
  }, {
    "name" : "app",
    "time" : {
      "start" : 1618228896928,
      "stop" : 1618228896969,
      "duration" : 41
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false,
    "stepsCount" : 0
  } ],
  "afterStages" : [ {
    "name" : "db::fin",
    "time" : {
      "start" : 1618228902188,
      "stop" : 1618228902188,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false,
    "stepsCount" : 0
  }, {
    "name" : "stop::fin",
    "time" : {
      "start" : 1618228902189,
      "stop" : 1618228902223,
      "duration" : 34
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [name=\"user\"]\n\n",
    "statusTrace" : "  File \"c:\\work_olga\\teach\\python_training\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Work_olga\\Teach\\python_training\\conftest.py\", line 82, in fin\n    fixture.session.ensure_logout()\n  File \"C:\\Work_olga\\Teach\\python_training\\fixture\\session.py\", line 26, in ensure_logout\n    self.logout()\n  File \"C:\\Work_olga\\Teach\\python_training\\fixture\\session.py\", line 21, in logout\n    wd.find_element_by_name(\"user\")\n  File \"c:\\work_olga\\teach\\python_training\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 496, in find_element_by_name\n    return self.find_element(by=By.NAME, value=name)\n  File \"c:\\work_olga\\teach\\python_training\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 976, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"c:\\work_olga\\teach\\python_training\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\work_olga\\teach\\python_training\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true,
    "hasContent" : true,
    "stepsCount" : 0
  } ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "test"
  }, {
    "name" : "suite",
    "value" : "test_add_group"
  }, {
    "name" : "host",
    "value" : "DESKTOP-H5JPLR0"
  }, {
    "name" : "thread",
    "value" : "6692-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test.test_add_group"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "json_groups",
    "value" : "None:nameUL;headerO6U9?.z8;&;footero`'a"
  } ],
  "links" : [ ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "6eaba313918cbcd8.json",
  "parameterValues" : [ "None:nameUL;headerO6U9?.z8;&;footero`'a" ]
}